### PR TITLE
Support for non-packed workflows

### PR DESCRIPTION
**Pull request by dleehr**
- Adds `type` field to WorkflowVersion
- Renames `object_name` to `workflow_path`
- Updates jobtemplate to handle string workflow versions (and removes explicit 'v' prefix)
- Updates lando-messaging to 1.0.0

### CODE REVIEW

**Comment by dleehr** [comment]
WIP, will try in dev with lando updates before requesting review.

**Comment by dleehr** [comment]
Ready for review now. bespin-dev job 104 ran as expected.

**Comment by dleehr** [comment]
Fixes #204

**Review by johnbradley — APPROVED** [review]
LGTM

**Pull request merged**
