### PR TITLE
Require a token before starting a job

### PR DESCRIPTION
**Pull request by johnbradley**
# Summary
Adds job tokens model to allow flexible control over users running jobs.
Introduces a new state of AUTHORIZED that is required before a user can start a job.

Job state changes after this PR (happy path):
- user creates job (state defaults to 'New')
- user sets `run_token` (state becomes 'Authorized')
- user starts job (state becomes 'Starting')
- lando starts job (state becomes 'Running')
- worker tells lando job is done (state becomes 'Finished')

### Admin endpoint `/api/admin/job-tokens/`
Admin users can see the list of tokens.
Admin can create tokens by sending POST to this endpoint with a payload like so:
```
{ "token": "<a_unique_token_value>" }
```

### User endpoint `/api/job/<job_id>/set_run_token/`
User can POST to this endpoint with a payload like so:
```
{ "token": "<unused_valid_token>" }
```
This changes the job state to 'Authorized'.

### CODE REVIEW

**Comment by johnbradley** [comment]
I'm not thrilled with the `set_run_token` part of the `/api/job/<job_id>/set_run_token/` endpoint. It would be nice if it could convey that the token will be used up.

**Comment by dleehr** [comment]
> I'm not thrilled with the `set_run_token` part of the `/api/job/<job_id>/set_run_token/` endpoint. It would be nice if it could convey that the token will be used up.

How about `/api/job/:job_id/authorize/`?

**Comment by johnbradley** [comment]
> How about /api/job/:job_id/authorize/?

Sounds good for now. This might get confusing if they have to authorize data delivery with another token.

**Comment by dleehr** [comment]
True - if that too is an action on the job. I believe last week we punted on the delivery authorization question. Some thoughts:

- We could use `/jobs/:job_id/authorize` for authorizing (approving) the job control and to release the data by posting a different type of payload on the same action endpoint. This is flexible but obtuse.
- From the API perspective, job control (start/stop/cancel) and data delivery are distinct enough that they could justify different endpoints.
- We could use two action endpoints, like `authorize_control` and `authorize_delivery` for the respective state changes

**Comment by johnbradley** [comment]
I agree that the delivery portion is outside of this PR.

I like this option the best:
> - From the API perspective, job control (start/stop/cancel) and data delivery are distinct enough that they could justify different endpoints.

Let's just leave this one at `authorize` and figure out the other endpoint when we get to it.

**Review by dleehr — APPROVED** [review]

**Pull request merged**
