### PR TITLE
Upgrade to Python 3.6

### PR DESCRIPTION
**Pull request by dleehr**
- Reworks base image Dockerfile build process - now `FROM python:3.6` instead of custom `quay.io/dukegcb/python-web-base:2.7-onbuild` base. Updates apt packages to python3 variants.
- Updates apache-docker/Dockerfile to install mod\_wsgi with pip. Updates apache conf to load this module.
- Updates CircleCI build to use python 3.6 base image for testing
- Fixes imports for python 3 style and removes `from future` imports
- Removes Mock from dependencies since it is in the language now
- Fixes byte-string name in merged migration that caused replacements not to be detected
- Code fixes for language changes:
  - [zip - now returns an iterator](https://docs.python.org/3/library/functions.html#zip)
  - [Exception no longer has a message attribute](https://www.python.org/dev/peps/pep-0352/#retracted-ideas)

### CODE REVIEW

**Comment by dleehr** [comment]
Tests pass and I've been able to run the apache image with postgres in a local docker-compose environment. Will test extensively on bespin-dev

**Comment by dleehr** [comment]
Fixes #156

**Review by johnbradley — APPROVED** [review]
LGTM

Looks like new migrations created by manage.py with python3 still import `unicode_literals` from `__future__`.

**Comment by dleehr** [comment]
> Looks like new migrations created by manage.py with python3 still import `unicode_literals` from `__future__`.

That was a suggestion from `2to3`. I wonder if it's worth reverting that change to clarify the things that are here - since Django will continue to add them

**Comment by johnbradley** [comment]
I'm pretty sure I will forget to remove the unicode_literals boilerplate at some point from future migrations.

**Pull request merged**
